### ISSUE TITLE
Repo needs updation

### ISSUE THREAD

**Issue by iamwatchdogs** [REC-CSE-LAB/DBMS_Lab#5]
# Issue Statement
In our DMBS lab, we have covered till Sub-Queries section and the current repo state is still under the "Conventional functions" session. 

## Skill required:
- Markdown Language

## Files needed Add:
The following are the files required to add to resolve this issue:

- Aggregate Functions
   - Concept Builder
   - Skill Builder
   - Challenge Yourself
- Sub-Queries
   - Concept Builder
   - Skill Builder
   - Challenge Yourself

<br />

> **Note** 
>
>> - Make sure you update all the mentioned Directories and files within it, with Required **Questions** and its **Answers**.
>
>> - Also make sure that you have followed the same pattern while updating the Repo,
>
>> - For reference, check out the previous PR *which is #2 PR*

<br />

**Comment by REC-SAM** [comment]
Please Reopen this Issue, this repo ***still needs updation***...
Please finish the `Joins and Normalization module` too..
Thank you...

**Comment by iamwatchdogs** [comment]
Thank you for the heads up @REC-SAM ...
